$ANSIBLE_VAULT;1.1;AES256
62666432613862613132386434663562396166626365366238666363396533393262643965393234
6439333836663330343531656262646333366130346465350a613961623638613434333566653361
38636663343766303737666538386330393364393934643239366137323837313033333866393433
6461356432626438370a383564616462343862663635383339623564663866646331626362343565
39356334623330356231663732323263623836323964323834373133326364353661383737653466
37333030353132333632343362393436383635343065353239353261616231613761303836643237
31636465643037356638383533633339623862646565393935366363323365313235353632646664
65363764303264386439393862393362336263663739346336373231663238333830393835373630
34356538383262356433656132643332313766343364383038353931356434393066656233633561
61306339643164376530646161626130376363306231626663353938663561353335376662363534
33353432393435383261613430303165656565623131313631396266383665356361313834656563
36396532303663393732363434366239303031303764663130356563663739653862653266393434
64633431646365323361626539343136643336393566313863303131613933626431313631613338
6338356534346133303933363030393332356330646130623431
