$ANSIBLE_VAULT;1.1;AES256
36353236656635343339646130316631663736363465323138363434666430373462666234383166
3262633166383035643633646165343335386565386465380a343466656162646239393663346334
33396561333061366533646630626665646164346665346239363531353637616461396166656663
3830306666366661340a373432666361626163333735323931336662326362643638666137353165
39613836393166623332626339633065663939636564353330626133333139613434303264303034
35396365393232323865383439333837306538383139653130313735383065316534316331666232
38653435396564356530613837646232376634326534376262303166613834663833383530613266
38653063376133653532633564643533363364376531626363633162393136623665663038643234
62353433616634343934383433353036626265333836616238633635616237376463633139376338
35346331326166373663666437313930353038626431626535636230333930373063343430653165
66643736616531353966326435666234366364323664663731656537393063306663383762636231
38366562313032323630626332336533616535316566303539363362346234336330663862386539
30396131316138623431663561396536646337306535623934633539383366303535656235663531
3162323337633635343064326638366564366432323930316664
