---

ansible_host: "{{ vault_ansible_host }}"
ansible_become_password: "{{ vault_ansible_become_password }}"

wireguard_server: "{{ vault_wireguard_server }}"
wireguard_peers: "{{ vault_wireguard_peers }}"

duckdns_domains: "{{ vault_duckdns_domains }}"
duckdns_token: "{{ vault_duckdns_token }}"
proxy_masked_domain: "{{ vault_proxy_masked_domain }}"
proxy_masked_email: "{{ vault_proxy_masked_email }}"

amneziawg_clients: "{{ vault_amneziawg_clients }}"
amneziawg_params: "{{ vault_amneziawg_params }}"
