$ANSIBLE_VAULT;1.1;AES256
66656636643535356234663237323561373038306530643839616438313330343232643466643637
3639353039396630633964373665633666366434323237350a626435343934623339623461323635
36663964616632633031663464613461343663366338663436303739613534376131353336343665
6265616532386165640a353931366530386331333966386631353530626462323438366139616262
62346236336236326165656231633533376436306231316164353532343864323335636465316365
33336233646332646663656466343032343066656331343538386335396538363433353537313064
62613839613337356133316366623336653634623934313935366536326261353362373530313035
65623333313836653532623565366439643263623965646333313235666163333665383761646132
36326432613939353661356263363731303062353634646461333663656137363365663337323932
31343462616333343063613966383630336630353332343837363166393338346535633539326265
65366566643637633737316632643332613963626637383163356235663537333432656661316531
39626466653361626530303064353931336231666335356362373133313530666135643861376365
36616263343138393066643539386235323361333563643834336331323866656365396230316164
61353132633633336536636466313334636364623936633463353136303664373337333438643538
66643665373137316637343832663763323830613031343637343266663764326561393664663134
33333732356164663738336264623733613030313364383436613838646136363235346564656164
32633863306535623437653664383662326362326364326266303839373939623162313933633137
36303337643466316263623564383561303933323464333437636563343166363162323932386639
64356232663661646537653966616531363637323164373533346263396433633239386165313862
30393165653730643261303435306463333733356234383833626431393735366631336234363664
37333832396638333365613331663538616135373565663131363332646337353765623937666434
38616266393866306537616265303637333639666435323739636435386639626336666434346461
35623035623761343132356639636566383535306433613764616634336563663732366165626632
37613664303833323964373639376332313035313363653265316138316364623863373939383266
3961
