$ANSIBLE_VAULT;1.1;AES256
30336563653732366432303564366434306561393064633839303033643631323134616537356536
3862366537626638363966366434653464656431373438380a323635383066666462306636303664
38346662626438626261663264663465633137663732343563303634383531306433616634646430
6165653165663839330a343865373735333935383532643361626435316139386661373239393435
34383363346231303064376462646638626139666238386532633033613033653462616662646134
34626533623239323566353464313266353433393436633830623433666539313234643438383033
32363061656634306433336166323464653234656234663064343530353562373565303335356364
61363537323061653265303662373734393734626537363335393665393938343262663434396139
32373061616435626566383030623763323666663237363232306439633466626235383539396538
66643439363764323037393536633432663034663935636634626139666333616137303738626530
62633864626430636435346461316265373232613861666238326339643835363765363838633730
65363461623738613231646234373030376264383663613737326264646136336632643338383337
38336331363531653934643039383138633136346164346239396232666638316231303464303664
3261393064386565306338306334623039343232633932636636
